security:

    encoders:
        CoreBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        user_db:
            entity: { class: CoreBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern: ^/
            provider: user_db
            form_login:
                login_path: /
                check_path: /login_check
                remember_me: true
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: ~




    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    # Estrategia de voters (por defecto affirmative)
    access_decision_manager:
        strategy: unanimous
